development:
  adapter: postgresql
  encoding: unicode
  database: testM_development
  pool: 5
  username: admin
  password:
  host: localhost



test:
  adapter: postgresql
  encoding: unicode
  database: testM_test
  pool: 5
  username: admin
  password:
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: testM_production
  pool: 5
  username: admin
  password:
  host: localhost